### ISSUE TITLE
There are so many different types of test. Which should be used when?

### ISSUE THREAD

**Issue by MegaBean** [estherthetester/ama#1]

**Comment by estherthetester** [comment]
Thanks for the question @MegaBean! This is a classic example of where the "it depends" answer is on point.

Therefore I'm going to make it relevant for my current place of work, Unruly. Unruly have a successful history of testing in production, roughly translating to not relying on a test/staging/preprod environment.

So in this case we could define _"when"_ as testing that happens before deploying (pre-production) and testing that happens after (production).

Cindy Sridharan has a great [article](https://medium.com/@copyconstruct/testing-in-production-the-safe-way-18ca102d0ef1) on this topic, and highlights some key testing types and when these might be used.

![alt text](https://cdn-images-1.medium.com/max/1600/1*LFnVVlLrgrvXQ5ScrHVKjg.jpeg "Logo Title Text 1")

Testing types aside, I am a huge fan of continuous testing (from unit tests, to testing your assumptions with stakeholders) and being conscious of if you are repeating it, automate it.

_If this answers your question, please close the issue._
